apiVersion: v1
kind: ConfigMap
metadata:
  name: datacore-config
  namespace: datacore
data:
  config.toml: |
    [broker]
    id = 1
    advertised_host = "datacore.production.local"
    port = 9092
    admin_port = 8080

    [storage]
    engine = "s3"
    dir = "/tmp/datacore"
    s3_path_style = true

    [auth]
    enabled = true

    [logging]
    level = "info"
    format = "json"